#!/bin/bash
. /var/openpanel/api/sh/module.sh

CronaptSettings.update() {
    doupdate=$(coreval CronaptSettings enabled)

    [ "$doupdate" = "true" ] && authd runscript openapp-configure-cron-apt on
    [ "$doupdate" = "false" ] && authd runscript openapp-configure-cron-apt off
}

Module.getconfig() {
  cat << _EOF_
  <openpanel.module>
    <dict id="CronaptSettings" type="class">
      <dict id="openapp-cronapt-settings" type="object">
        <bool id="enabled">true</bool>
      </dict>
    </dict>
	<dict id="OpenCORE:Result">
      <integer id="error">0</integer>
      <string id="message">OK</string>
    </dict>
  </openpanel.module>
_EOF_
  exitquiet
}

implement OpenAppCronapt.module
